CuaHangCongNghe/Controllers/CartController.cs
using CuaHangCongNghe.Repository;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace CuaHangCongNghe.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
       
        private readonly IProductService productService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderItemService OrderItemService;
        private readonly IUserService userService;

        public CartController(IOrderItemService OrderItemService, IProductService productService, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            this.OrderItemService = OrderItemService;
            this.productService = productService;
            this.userManager = userManager;
            this.userService = userService;
        }

        public  IActionResult Index()
        {
            var orderViewModel =  OrderItemService.GetOrderPay(userManager.GetUserId(User));
            return View(orderViewModel);
        }

        public  IActionResult Add(int id)
        {
            
            var IdUser = userManager.GetUserId(User);
            
            var product = productService.GetProduct(id);
            var user  = userService.GetUserl(IdUser);
           
            if (user == null)
            {
                userService.createUser(IdUser);
            }
           
            OrderItemService.AddCart(product, IdUser);
            return RedirectToAction("Index");
        }

        public  IActionResult Update(Dictionary<int, int> items)
        {
            var user =  userManager.GetUserId(User);



            foreach (var item in items)
            {
               
                OrderItemService.UpdateQuantity(user, item.Key, item.Value);
            }

            return RedirectToAction("Index");
        }

        public IActionResult DeleteItem(int itemId)
        {
            OrderItemService.DeleteItem(userManager.GetUserId(User), itemId);
            return RedirectToAction("Index");
        }

    }
}

CuaHangCongNghe/Controllers/HomeController.cs
using CuaHangCongNghe.Extensions;
using CuaHangCongNghe.Models;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Mvc;


namespace CuaHangCongNghe.Controllers
{
    public class HomeController : Controller
    {

        private const int pageSize = 12;
        private const int maxPages = 5;
        private readonly IProductService productService;

        public IActionResult Themes()
        {
            return View();
        }

        public HomeController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index(int page)
        {
            var products = productService.GetAllProducts();
            var pager = CreatePagination(products, page);
            return View(pager);
        }

        private PagerViewModel CreatePagination(List<ProductViewModel> products, int currentPage)
        {
            var productsOnCurrentPage = products.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();
            var totalPages = (int)Math.Ceiling((decimal)products.Count / (decimal)pageSize);
            if (currentPage < 1)
            {
                currentPage = 1;
            }
            else if (currentPage > totalPages)
            {
                currentPage = totalPages;
            }
            int startPage, endPage;
            if (totalPages <= maxPages)
            {
                startPage = 1;
                endPage = totalPages;
            }
            else
            {
                var maxPagesBeforeCurrentPage = (int)Math.Floor((decimal)maxPages / (decimal)2);
                var maxPagesAfterCurrentPage = (int)Math.Ceiling((decimal)maxPages / (decimal)2) - 1;
                if (currentPage <= maxPagesBeforeCurrentPage)
                {
                    startPage = 1;
                    endPage = maxPages;
                }
                else if (currentPage + maxPagesAfterCurrentPage >= totalPages)
                {
                    startPage = totalPages - maxPages + 1;
                    endPage = totalPages;
                }
                else
                {
                    startPage = currentPage - maxPagesBeforeCurrentPage;
                    endPage = currentPage + maxPagesAfterCurrentPage;
                }
            }
            var pages = Enumerable.Range(startPage, (endPage + 1) - startPage);
            return new PagerViewModel()
            {
                TotalItems = products.Count,
                CurrentPage = currentPage,
                PageSize = pageSize,
                TotalPages = totalPages,
                StartPage = startPage,
                EndPage = endPage,
                Pages = pages,
                ProductsOnCurrentPage = productsOnCurrentPage
            };
        }

        public IActionResult Search(string name)
         {
             var products = productService.GetAllProducts();
             var searchProducts = new List<ProductViewModel>();
             if (!string.IsNullOrEmpty(name))
             {
                 name = name.ToUpper();
                 searchProducts = products.Where(x => x.Name.ToUpper().Contains(name)).ToList();
             }
             return View(searchProducts);
         }
    }
}

CuaHangCongNghe/Controllers/ProductController.cs
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Mvc;

using System;

namespace CuaHangCongNghe.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index(int id)
        {
            var product = productService.GetProduct(id);
            return View(product);
        }
    }
}

CuaHangCongNghe/Views/Home/Index.cshtml
@model CuaHangCongNghe.Models.PagerViewModel

<div class="row">
    <div class="col-12">

        <div class="d-flex justify-content-center my-4" >
            <form method="get" asp-controller="Home" asp-action="Search" class="input-group col-10">
                <input type="text" name="name" class="form-control" placeholder="tìm kiếm" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-dark" href="" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 15 18">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
<div class="row">
    <div class="col-12">
            <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img src="/images/18001771.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img src="/images/—Pngtree—cool new mobile phone promotion_1006678.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img src="/images/18001771.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        <div class="row">
       
                <div class="gallery" id="gallery">
                    @foreach (var product in Model.ProductsOnCurrentPage)
                    {
                        if (product.Stockquantity > 0)
                        {
                          

                            <div class="content">
                                <a asp-controller="Product" asp-route-id="@product.Id"><img style="margin-top:10px"  src="@Url.Content(product.ImageUrl)" alt="hình ảnh sản phẩm"></a>
                            <a class="b" asp-controller="Product" asp-route-id="@product.Id"><h3>@product.Name</h3></a>
                                <h6 style="color:black">giá:@product.Price VNĐ</h6>
                                <p>Số lượng:@product.Stockquantity</p>

                            <a asp-controller="Cart" asp-action="Add" style=" text-decoration: none;" asp-route-id="@product.Id" role="button"><h3>ADD TO CART </h3></a>
                            </div>

                        }
                    }
                </div>
          
        </div>
    </div>
</div>
    </div>
 
<nav>
    <ul class="pagination justify-content-center mt-4">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link text-dark" asp-action="Index" asp-route-page="@(Model.CurrentPage - 1)">sau</a>
            </li>
        }
        @if (!Model.HasPreviousPage)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">sau</a>
            </li>
        }
        @foreach (var pageNumber in Model.Pages)
        {
            @if (pageNumber == Model.CurrentPage)
            {
                <li class="page-item active"><a asp-action="Index" asp-route-page="@pageNumber" class="page-link bg-info border-info  text-white">@pageNumber</a></li>
            }
            else
            {
                <li class="page-item"><a asp-action="Index" asp-route-page="@pageNumber" class="page-link text-dark">@pageNumber</a></li>
            }
        }

        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a class="page-link text-dark" asp-action="Index" asp-route-page="@(Model.CurrentPage + 1)">sau</a>
            </li>
        }
        @if (!Model.HasNextPage)
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">trước</a>
            </li>
        }
    </ul>
</nav>

CuaHangCongNghe/Views/Home/Search.cshtml
@model List<CuaHangCongNghe.Models.ProductViewModel>

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-center my-4">
            <form asp-controller="Home" asp-action="Search" class="input-group col-10">
                <input type="text" name="name" class="form-control" placeholder="tìm kiếm" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-dark" href="" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 15 18">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselIndicators" data-slide-to="1"></li>
                <li data-target="#carouselIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img src="/images/18001771.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img src="/images/—Pngtree—cool new mobile phone promotion_1006678.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img src="/images/18001771.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="row">
            @foreach (var product in Model)
            {
                <div class="col-3 mt-4">
                    <div class="card h-100 box-shadow">
                        <a asp-controller="Product" asp-action="Index" asp-route-id="@product.Id"><img class="card-img-top" src="@Url.Content(product.ImageUrl)" alt="hình ảnh sản phẩm"></a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a class="text-dark" asp-controller="Product" asp-action="Index" asp-route-id="@product.Id">@product.Name</a>
                            </h4>
                            <h5>@product.Price &#8381;</h5>
                            <p class="card-text">@product.Description</p>
                        </div>
                        <div class="card-body d-flex align-items-end">
                            <a class="btn btn-info" asp-controller="Cart" asp-action="Add" asp-route-id="@product.Id" role="button">thêm vào giỏ hàng</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

CuaHangCongNghe/Views/Home/Themes.cshtml
@{
    Layout = null;
}
<head>
    <meta charset="UFT-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Animad wedsite html css | Codehal </title>
    <link rel="stylesheet" href="/css/sty.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>

<body>

    <header class="header">
        <a href="#" class="logo">Cart.</a>

        <nav class="navbar">
            <a href="#" style="--i:1;" class="active">Home</a>
            <a href="#" style="--i:2;">About</a>
            <a href="#" style="--i:3;">Review</a>
            <a href="#" style="--i:4;">Home</a>
            <a href="#" style="--i:5;">Feature</a>
            <a href="#" style="--i:6;">Contact</a>
        </nav>
        <div class="social-media">
            <a href="#" style="--i:1;"><i class='bx bxl-twitter'></i></a>
            <a href="#" style="--i:2;"><i class='bx bxl-instagram-alt'></i></a>
            <a href="#" style="--i:3;"><i class='bx bxl-facebook-circle'></i></a>
        </div>

    </header>





    <section class="home">
        <div class="home_content">
            <h1>Cart Dealing Experience.</h1>
            <h3>Rederfined</h3>
            <p>asdfsadf adsfa asdf adfa adsfa adf</p>
            <a href="#" class="btn">Explore</a>
        </div>
        <div class="home-img">
            <div class="rhombus">
                <img src="/images/pngimg.com - porsche_PNG10629.png" alt="">
            </div>
        </div>
        <div class="rhombus2"></div>
    </section>



</body>