CuaHangCongNghe/Controllers/CartController.cs
using CuaHangCongNghe.Repository;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace CuaHangCongNghe.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
       
        private readonly IProductService productService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderItemService OrderItemService;
        private readonly IUserService userService;

        public CartController(IOrderItemService OrderItemService, IProductService productService, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            this.OrderItemService = OrderItemService;
            this.productService = productService;
            this.userManager = userManager;
            this.userService = userService;
        }

        public  IActionResult Index()
        {
            var orderViewModel =  OrderItemService.GetOrderPay(userManager.GetUserId(User));
            return View(orderViewModel);
        }

        public  IActionResult Add(int id)
        {
            
            var IdUser = userManager.GetUserId(User);
            
            var product = productService.GetProduct(id);
            var user  = userService.GetUserl(IdUser);
           
            if (user == null)
            {
                userService.createUser(IdUser);
            }
           
            OrderItemService.AddCart(product, IdUser);
            return RedirectToAction("Index");
        }

        public  IActionResult Update(Dictionary<int, int> items)
        {
            var user =  userManager.GetUserId(User);



            foreach (var item in items)
            {
               
                OrderItemService.UpdateQuantity(user, item.Key, item.Value);
            }

            return RedirectToAction("Index");
        }

        public IActionResult DeleteItem(int itemId)
        {
            OrderItemService.DeleteItem(userManager.GetUserId(User), itemId);
            return RedirectToAction("Index");
        }

    }
}

CuaHangCongNghe/Controllers/UserProfileController.cs
using CuaHangCongNghe.Models;
using CuaHangCongNghe.Repository;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.viewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using CuaHangCongNghe.Extensions;


namespace CuaHangCongNghe.Controllers
{
   // [Authorize(Policy = "UserAccess")]
    public class UserProfileController : Controller
    {
    
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderItemService  OrderItemService;
        public UserProfileController(UserManager<ApplicationUser> userManager, IOrderItemService OrderItemService)
        {
            this.userManager = userManager;
            this.OrderItemService = OrderItemService;
           
        }

        public async Task<IActionResult> Index()
        {
            var user = await userManager.FindByIdAsync(userManager.GetUserId(User));
            var model = new UserViewModel { Id = user.Id, EmailUser = user.Email, NameUser = user.Name, PhoneUser = user.PhoneNumber,RegistrationDate = user.DateTime,AddressUser = user.Address };
            return View(model);

          
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new UserViewModel { Id = user.Id, EmailUser = user.Email, NameUser = user.Name, PhoneUser = user.PhoneNumber, RegistrationDate = user.DateTime, AddressUser = user.Address };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {              
           
            if (model != null)
            {
                var user = await userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    
                    user.Email = model.EmailUser;
                    user.Name = model.NameUser;
                    user.PhoneNumber = model.PhoneUser;
                    user.Address = model.AddressUser;                   
                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        result.AddErrorsTo(ModelState);
                    }
                }
           }
            return View(model);
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new UserViewModel { Id = user.Id, EmailUser = user.Email, NameUser = user.Name, PhoneUser = user.PhoneNumber, RegistrationDate = user.DateTime, AddressUser = user.Address };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(UserViewModel model)
        {
            
            if (ModelState.IsValid)
            {                             
                var user = await userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var result = await userManager.ChangePasswordAsync(user, model.Password, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        result.AddErrorsTo(ModelState);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "vui lòng nhập thông tin");
                }
            }
            return View(model);
        }
        public async Task<IActionResult> GetAllOrders(int? status)
        {
         
            var user = await userManager.FindByIdAsync(userManager.GetUserId(User));
            var model = new UserViewModel { Id = user.Id };
            var Orders = new UserOrdersViewModel { User = model };

   
          
            if (status == null)
            {
                Orders.Orders = OrderItemService.GetCurrentAllOrderUser(user.Id);
            }
            if (status != null)
            {
                Orders.Orders = OrderItemService.GetCurrentAllOrderUser(user.Id).Where(c => c.Status == status).ToList();
            }

            return View(Orders);
        }
        public async Task<IActionResult> fragment(int? status)
        {

            var user = await userManager.FindByIdAsync(userManager.GetUserId(User));
            var model = new UserViewModel { Id = user.Id };
            var Orders = new UserOrdersViewModel { User = model };



            if (status == null)
            {
                Orders.Orders = OrderItemService.GetCurrentAllOrderUser(user.Id);
            }
            if (status != null)
            {
                Orders.Orders = OrderItemService.GetCurrentAllOrderUser(user.Id).Where(c => c.Status == status).ToList();
            }

            return View(Orders);
        }



        public async Task<ActionResult> GetItemOrder(int id)
        {
            var user = await userManager.FindByIdAsync(userManager.GetUserId(User));
            var model = new UserViewModel { Id = user.Id, EmailUser = user.Email, NameUser = user.Name, PhoneUser = user.PhoneNumber, RegistrationDate = user.DateTime, AddressUser = user.Address };
            var items = new UserOrderViewModel();
            var order = OrderItemService.GetOrder(id);

            items.Order = order;
            items.User = model;


            return View(items);
        }
    }
}

CuaHangCongNghe/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="/css/sty.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

CuaHangCongNghe/Views/Shared/FooterPartial.cshtml
<footer class="footer bg-dark text-white-50" style="  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  text-align: center;">
    <div class="container text-center">
        <small>&copy; @DateTime.Now.ToString("dddd, dd MMMM yyyy hh:mm tt") CellPhone Universe</small>
    </div>
</footer>

CuaHangCongNghe/Views/Shared/HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">CellPhone Universe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="GetOrders" role="button" aria-haspopup="true" aria-expanded="false">
                                admin dashboard
                            </a>
                        </li>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <form method="get" class="form-inline my-2 my-lg-0">
                                <button class="btn btn-dark" type="submit" asp-controller="Account" asp-action="Login">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z" />
                                        <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                                    </svg>
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                </svg>
                            </a>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item">
                                    <form method="get" asp-controller="UserProfile" asp-action="Index">
                                        <input type="submit" value="Cá Nhân" style="background:none;border:none;padding:0">
                                    </form>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item">
                                    <form method="post" asp-controller="Account" asp-action="Logout">
                                        <input type="submit" value="Đăng xuất" style="background:none;border:none;padding:0">
                                    </form>
                                </a>
                            </ul>
                        </li>
                    }
                    <li class="nav-item">
                        <form method="get" class="form-inline my-2 my-lg-0">
                            <button class="btn btn-dark" type="submit" asp-controller="Cart" asp-action="Index">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart2" viewBox="0 0 20 19">
                                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                                </svg>
                                <span class="visually-hidden"><strong>@await Component.InvokeAsync("Cart", User.Identity.Name)</strong></span>
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

CuaHangCongNghe/Views/Shared/LayoutAdmin.cshtml
<!DOCTYPE HTML>
<html lang="en" charset="UTF-8">

<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body data-bs-theme="light" style="" >
    @await Html.PartialAsync("HeaderPartial")
    <link rel="stylesheet" href="/css/admin.css">
    <div class="container">
        <main role="main" class="pb-3"  >
            <div class="row" >
            <div class="col-md-4">
        @await Html.PartialAsync("adminDashboard")
        </div>
                <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                <script src="/js/chart.js" type="text/javascript"></script>
            @RenderBody()
        
        </div>
        </main>
    </div>
    @await Html.PartialAsync("FooterPartial")
    @await Html.PartialAsync("ScriptsPartial")
    @RenderSection("Scripts", required: false)
</body>
</html>

CuaHangCongNghe/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] CellPhone Universe</title>

CuaHangCongNghe/Views/Shared/ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/user.js" asp-append-version="true"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

CuaHangCongNghe/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en" >
<meta charset="UTF-8">
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body data-bs-theme="light">
    @await Html.PartialAsync("HeaderPartial")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("FooterPartial")
    @await Html.PartialAsync("ScriptsPartial")
    @RenderSection("Scripts", required: false)
   
</body>
</html>

CuaHangCongNghe/Views/Shared/adminDashboard.cshtml
<div class="card" style="width: 18rem;">
    <div class="col-md-4">
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item ">
                    <a asp-action="GetUsers" class="material-symbols-outlined">group<i>Quản lý người dùng</i></a>
            </li>
            <li class="list-group-item">
                    <a asp-action="GetOrders" class="material-symbols-outlined">List<i>Quản lý đơn hàng</i></a>
            </li>
            <li class="list-group-item">
                    <a asp-action="GetRoles" class="material-symbols-outlined">Settings_Accessibility<i>Quản lý quyền truy cập</i></a>
            </li>
            <li class="list-group-item">
                    <a asp-action="AllProduct" class="material-symbols-outlined">apps<i>Quản lý sản phẩm</i></a>
            </li>
            <li class="list-group-item">
                    <a asp-action="AddProduct" class="material-symbols-outlined">add<i>Thêm sản phẩm</i></a>
            </li>
        </ul>
    </div>
</div>
</div>