CuaHangCongNghe/Controllers/CartController.cs
using CuaHangCongNghe.Repository;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace CuaHangCongNghe.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
       
        private readonly IProductService productService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderItemService OrderItemService;
        private readonly IUserService userService;

        public CartController(IOrderItemService OrderItemService, IProductService productService, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            this.OrderItemService = OrderItemService;
            this.productService = productService;
            this.userManager = userManager;
            this.userService = userService;
        }

        public  IActionResult Index()
        {
            var orderViewModel =  OrderItemService.GetOrderPay(userManager.GetUserId(User));
            return View(orderViewModel);
        }

        public  IActionResult Add(int id)
        {
            
            var IdUser = userManager.GetUserId(User);
            
            var product = productService.GetProduct(id);
            var user  = userService.GetUserl(IdUser);
           
            if (user == null)
            {
                userService.createUser(IdUser);
            }
           
            OrderItemService.AddCart(product, IdUser);
            return RedirectToAction("Index");
        }

        public  IActionResult Update(Dictionary<int, int> items)
        {
            var user =  userManager.GetUserId(User);



            foreach (var item in items)
            {
               
                OrderItemService.UpdateQuantity(user, item.Key, item.Value);
            }

            return RedirectToAction("Index");
        }

        public IActionResult DeleteItem(int itemId)
        {
            OrderItemService.DeleteItem(userManager.GetUserId(User), itemId);
            return RedirectToAction("Index");
        }

    }
}

CuaHangCongNghe/Controllers/CheckOutController.cs
using Azure;
using CuaHangCongNghe.laydulieu;
using CuaHangCongNghe.Models;

using CuaHangCongNghe.Repository;
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using CuaHangCongNghe.viewModel;
using log4net;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;



namespace Shop.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly IUserService  userService;
        private readonly IProductService productService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IOrderItemService  OrderItemService;
        private readonly IPaymentService paymentService;
        private readonly IConfiguration _configuration;
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private static UserOrderViewModel userOrderViewModel;
        public CheckOutController(IPaymentService paymentService,IOrderItemService oderItemService, IUserService userService, IProductService productService, UserManager<ApplicationUser> userManager, IConfiguration configuration)
        {
            this.OrderItemService = oderItemService;
            this.userManager = userManager;
            this.productService = productService;
            this.userService = userService;
            _configuration = configuration;
            this.paymentService = paymentService;
        }


        public IActionResult Pay()
        {
         

            return View(userOrderViewModel);
            
        }
     
        public async Task<IActionResult> CreateItemOrder()
        {
            var user = await userManager.FindByIdAsync(userManager.GetUserId(User));

            var  userOrderView = new UserOrderViewModel();
            ProductViewModel product;

         
                userOrderView.Order = OrderItemService.GetOrderPay(user.Id);

      
            

            userOrderView.User = new UserViewModel { Id = user.Id, EmailUser = user.Email, NameUser = user.UserName, PhoneUser = user.PhoneNumber, RegistrationDate = user.DateTime, AddressUser = user.Address };
            userOrderViewModel = userOrderView;
            return View(userOrderView);
        }



        [HttpPost]
        public IActionResult SaveOrder(UserOrderViewModel model)
        {

            userService.AddInformation(userManager.GetUserId(User), model.User);
            

          
            return RedirectToAction("Pay");
        }

         
        [HttpPost]
        [Route("api/v1/payment")]
        public async Task<IActionResult> Payment(string status)
        {
           
                var user = userService.GetUser(userManager.GetUserId(User));
            // PaymentService paymentService =  new PaymentService(_configuration,OrderItemService);
                var userOrderView = new UserOrderViewModel();
                ProductViewModel product;

               
                
                  
               userOrderView.Order = OrderItemService.GetOrderPay(userManager.GetUserId(User));

            


                userOrderView.User = user;

            if (status == "1")
            {

                if (userOrderView != null)
                {
                    var respone = paymentService.PaymentCall(userOrderView);
                    if (!string.IsNullOrEmpty(respone))
                    {
                        return Redirect(respone);
                    }
                }
                return NotFound();
            }
            if(status == "2")
            {
                OrderItemService.ChangeStatus(userOrderView.Order.Id,2);
                foreach(var itemOrder in userOrderView.Order.ItemViewModels)
                {
                    productService.UpdateProduct(itemOrder.Product.Id, itemOrder.quantity);
                }
                
            }

            return RedirectToAction("Index", "Cart");
        }



        [HttpGet]
        public ActionResult ResponseVnp()
        {

            string queryString = Request.QueryString.ToString();

            var response = paymentService.CheckPaymentStatus(userManager.GetUserId(User), queryString);
            return View(response);


        }
    }
}

CuaHangCongNghe/Controllers/ProductController.cs
using CuaHangCongNghe.Service;
using CuaHangCongNghe.Services;
using Microsoft.AspNetCore.Mvc;

using System;

namespace CuaHangCongNghe.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index(int id)
        {
            var product = productService.GetProduct(id);
            return View(product);
        }
    }
}

CuaHangCongNghe/Views/Cart/Index.cshtml
@model CuaHangCongNghe.Models.OrderViewModel

@if (Model.ItemViewModels != null)
{
    <form method="post">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-12">
                <div class="py-4 text-center">
                    <h2><b>Giỏ hàng</b></h2>
                    <p class="text-center font-weight-light">
                        <i class="font-weight-bold text-info"> Số lượng hàng hóa trong giỏ hàng:@Model.FullAmount</i>
                    </p>
                </div>
                <table class="table table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th style="width:60%">Các mặt hàng</th>
                            <th style="width:12%">Giá</th>
                            <th style="width:10%">Số lượng</th>
                            <th style="width:16%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.ItemViewModels.Count; i++)
                        {
                            var item = Model.ItemViewModels[i];
                            <tr>
                                <td>
                                    <div class="row">
                                        <div class="col-md-3 text-left">
                                            <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Product.Id">
                                                <img src="@Url.Content(item.Product.ImageUrl)" alt="" class="img-fluid d-none d-md-block rounded mb-2 shadow">
                                            </a>
                                        </div>
                                        <div class="col-md-9 text-left mt-sm-2">
                                            <a class="text-info" asp-controller="Product" asp-action="Index" asp-route-id="@item.Product.Id"><h4>@item.Product.Name</h4></a>
                                            <p class="font-weight-light"></p>
                                        </div>
                                    </div>
                                </td>
                                <td><h5>@item.Price ₫ </h5></td>
                                <td>
                                    <input type="hidden" name="@("Items[" + i + "].Key")" value="@item.Id" />
                                    <input type="number" min="1" max="@item.Product.Stockquantity" class="form-control text-center" name="@("Items[" + i + "].Value")" value="@item.quantity">
                                    <p class="text-center"><small><h6>@item.Product.Price ₫ </h6></small></p>
                                </td>
                                <td class="actions">
                                    <div class="text-right">
                                        <button class="form-control" asp-action="Update">
                                            <i class="bi bi-arrow-repeat"></i>
                                        </button>
                                        <a class="btn  border-secondary btn-md mb-2" asp-action="DeleteItem" asp-route-itemId="@item.Id" role="button"><i class="bi bi-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="float-right text-right">
                    <h4>Tổng cộng:</h4>
                    <h2>@Model.FullPrice ₫ </h2>
                </div>
            </div>
        </div>
    </form>
    <form>
        <div class="row mt-4 d-flex align-items-center">
            <div class="col-sm-6 order-md-2 text-right">
               
                @if (Model.ItemViewModels.Count > 0) {
                    <button class="btn btn-info mb-4 btn-lg pl-5 pr-5" type="submit" asp-controller="CheckOut" asp-action="CreateItemOrder">
                        thủ tục thanh toán
                </button>
                }
            </div>
            <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
                <a class="text-info" asp-controller="Home" asp-action="Index"><i class="bi bi-arrow-left mr-2 text-info"></i>Tiếp túc mua sắm</a>
            </div>
        </div>
    </form>
}
else
{
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <div class="starter-template py-5 text-center">
                <h2><b>Giỏ hàng trống</b></h2>
                <p class="lead"><a class="text-info" asp-controller="Home" asp-action="Index">Nhấp vào đây</a> để tiếp tục mua sắm...</p>
            </div>
        </div>
    </div>
}